### ISSUE TITLE
https://realtime-pizza.tk/ not working

### ISSUE THREAD

**Issue by zaidajani** [deep-sangani/Realtime-Pizza-website#1]
## Problem

As we go to <a href="https://realtime-pizza.tk/'>https://realtime-pizza.tk/</a>, it gives `This site can’t be reached` error
![not working](https://user-images.githubusercontent.com/55057446/108219030-519ae380-715b-11eb-9af3-ed0012ead398.PNG)

**Comment by deep-sangani** [comment]
yes because my aws account was suspended because of billing issues 😭😭😭😭

**Comment by zaidajani** [comment]
Ok, it is fine 😂
